FROM ubuntu:latest

RUN echo build started 

RUN apt-get update

RUN apt install nano

WORKDIR /home/

RUN mkdir folder

RUN touch file.txt

RUN bash -c "echo 'hello world. this is abhinav' >> file.txt"

RUN echo build completed.